# -*- coding: utf-8 -*-
"""ann pracyice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0C1dtrz39uMOZMdmM6SbL3ss1uXkWQI
"""

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

mnist = fetch_openml('mnist_784', version = 1 ,as_frame= False)
x,y = mnist.data /255.0 , mnist.target.astype(int)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)
x_train.reshape(-1,1)
x_test.reshape(-1,1)

param_grid = {
    'alpha' : [1e-5 , 1e-4],
    'batch_size': [64,128],
    'learning_rate_init': [0.001,0.01],
    'solver': ['adam','sgd']
}

mlp = MLPClassifier(max_iter = 5, random_state = 42)

grid = GridSearchCV(mlp,param_grid, cv = 3 , n_jobs = 1,verbose = 1)
grid.fit(x_train,y_train)

best_model = grid.best_estimator_
y_pred = best_model.predict(x_test)

print("best parameters:"grid.best_params_)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("confusion matrix:")
print(confusion_matrix(y_test,y_pred))
print("classification report:")
print(classification_report(y_test,y_pred))

plt.figure(figsize=(10,6))
sns.heatmap(confusion_matrix(y_test,y_pred),annot=True,fmt='d',cmap='Blues')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

x , y = make_classification(n_samples = 100 , n_features = 10 , n_classes= 2, random_state = 42)

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)

model_overfit = Sequential([
    Dense(64,activation = 'relu',input_shape = (10,)),
    Dense(32,activation = 'relu'),
    Dense(2,activation = 'softmax')
])

model_overfit.compile(optimizer = 'adam',loss = 'categorical_crossentropy',metrics=['accuracy'])
history_overfit = model_overfit.fit(x_train,y_train_cat,epochs = 5 , validation_data= (x_test,y_test_cat),verbose = 1)

model_dropout = Sequential([
    Dense(64,activation = 'relu',input_shape = (10,)),
    Dropout(0.5),
    Dense(32,activation = 'relu'),
    Dropout(0.5),
    Dense(2,activation = 'softmax')
])

model_dropout.compile(optimizer = 'adam',loss = 'categorical_crossentropy',metrics=['accuracy'])

history_dropout = model_dropout.fit(x_train,y_train_cat,epochs = 5 , validation_data= (x_test,y_test_cat),verbose = 1)

plt.figure(figsize = (12,6))
plt.subplot(1,2,1)
plt.plot(history_overfit.history['loss'],label = 'Training Loss')
plt.plot(history_overfit.history['val_loss'],label = 'Validation Loss')
plt.plot(history_dropout.history['loss'],label = 'Training Loss')
plt.plot(history_dropout.history['val_loss'],label = 'Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend()

plt.figure(figsize = (12,6))
plt.subplot(1,2,1)
plt.plot(history_overfit.history['accuracy'],label = 'Training Accuracy')
plt.plot(history_overfit.history['val_accuracy'],label = 'Validation Accuracy')
plt.plot(history_dropout.history['accuracy'],label = 'Training Accuracy')
plt.plot(history_dropout.history['val_accuracy'],label = 'Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Training and Validation Accuracy')
plt.legend()

y_pred_dropout= np.argmax(model_dropout.predict(x_test),axis = 1)
print(")Accuracy:",accuracy_score(y_test,y_pred_dropout))
print("confusion matrix:")
print(confusion_matrix(y_test,y_pred_dropout))
print("classification report:")
print(classification_report(y_test,y_pred_dropout))

cm_overfit = confusion_matrix(y_test,np.argmax(y_test_cat,axis = 1))
sns.heatmap(cm_overfit,annot=True,fmt='d',cmap='Blues')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')

cm_dropout = confusion_matrix(y_test,y_pred_dropout)
sns.heatmap(cm_dropout,annot=True,fmt='d',cmap='Blues')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')

